package it.unito.di.sarlexceptions.test.exceptions

import io.sarl.api.core.Failure

event MyOtherException extends Failure {
	
	var e : Exception

}
